export enum tryThis {
    VEHICLE_TYPES = ' SELECT rug.IDUSAGEVEHICULE , ru.LIBELLE AS Usage_Vehicule , rg.LIBELLE AS Libelle_Genre  ,rug.IDGENRE FROM REF_USAGEVEHICULE_GENRE rug ,REF_USAGEVEHICULE ru, REF_GENRE rg WHERE ru.ID = rug.IDUSAGEVEHICULE AND rg.ID = rug.IDGENRE ; ',
    FISCAL_POWERS = 'SELECT ru.ID , ru.LIBELLE, rpf.id, rpf.PUISSANCE , rpf.IDUSAGEVEHICULE FROM REF_USAGEVEHICULE ru, REF_PUISSANCE_FISCALE rpf WHERE rpf.IDUSAGEVEHICULE = ru.ID ;',
    PLATE_TYPES = 'SELECT ru.ID AS Id , ru.LIBELLE AS Sous_Type_Usage , rpf.ID AS Id_Puissance_Fiscale , rpf.PUISSANCE AS Puissance_Fiscale  FROM REF_USAGEVEHICULE ru , REF_PUISSANCE_FISCALE rpf WHERE ru.ID =rpf.IDUSAGEVEHICULE ; ',
    hh = ''
  }

  